### ISSUE TITLE
Loading with Mac

### ISSUE THREAD

**Issue by EmilyMB** [ankane/gslr#1]
Thank you so much for creating this wrapper! I was looking for a simple Ruby interface for linear regression modeling, and this does the trick! 

I did have problems initially with getting this to work, in case anyone comes across this.

Relavant info:
macOS Sonoma (14.6.1)
gsl installed via hombrew
ruby 3.3.4

The errors were:
`GSL CBLAS not found (LoadError)...dlopen(libgslcblas.dylib, 0x0009)`
and 
 `dlopen(libgsl.dylib, 0x0009): tried: 'libgsl.dylib`

 which turns out was coming from this [code block](https://github.com/ankane/gslr/blob/c5ef7b839b070ed1c245df318c5cef5d1c24eeac/lib/gslr.rb#L24)

(My `RbConfig::CONFIG["host_os"]` = `darwin23` and `RbConfig::CONFIG["host_cpu"]` = `x86_64`)

My workaround was to set up symlinks:
`ln -s /usr/local/lib/libgsl.dylib libgsl.dylib`
`ln -s /usr/local/lib/libgslcblas.dylib libgslcblas.dylib`

**Comment by ankane** [comment]
Hi @EmilyMB, thanks for reporting! Fixed in the commit above.
